sudo: required

language: node_js
node_js:
  - "node"

branches:
  only:
    - production
    - master
    - bibek/ci # TODO: Remove once done testing

before_deploy:
  yarn build

deploy:
  provider: script
  script: deploy.sh
  on:
    all_branches: true



