sudo: required

language: node_js
node_js:
  - "iojs"
  - "7"

branches:
  only:
    - production
    - master
    - bibek/ci # TODO: Remove once done testing

before_deploy:
  yarn build

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "bruinmeet-staging-app"
    local_dir: build
    on:
      branch: bibek/ci
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "bruinmeet-production-app"
    local_dir: build
    on:
      branch: production

