sudo: required

language: node_js
node_js:
  - "node"

services:
  - docker

branches:
  only:
    - production
    - master
    - bibek/ci # TODO: Remove once done testing

before_install:
  - chmod +x deploy.sh
  - ./deploy.sh
