// @flow

export const UPDATE_AUTH: 'UPDATE_AUTH' = 'UPDATE_AUTH'
export const GET_USER: 'GET_USER' = 'GET_USER'
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS'
export const MARK_USER_INACTIVE: 'MARK_USER_INACTIVE' = 'MARK_USER_INACTIVE'
export const MARK_USER_VERIFIED: 'MARK_USER_VERIFIED' = 'MARK_USER_VERIFIED'
export const GET_MATCH_SUCCESS: 'GET_MATCH_SUCCESS' = 'GET_MATCH_SUCCESS'
export const GET_MATCHED_USER_SUCCESS: 'GET_MATCHED_USER_SUCCESS' = 'GET_MATCHED_USER_SUCCESS'
export const GET_RECENT_MATCHES_SUCESS: 'GET_RECENT_MATCHES_SUCCESS' = 'GET_RECENT_MATCHES_SUCCESS'
export const UPDATE_USER_PROFILE_PIC_SUCCESS: 'UPDATE_USER_PROFILE_PIC_SUCCESS' = 'UPDATE_USER_PROFILE_PIC_SUCCESS'

export const GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS' = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_MATCHES_SUCCESS: 'GET_ALL_MATCHES_SUCCESS' = 'GET_ALL_MATCHES_SUCCESS'
export const SET_RENDEZVOUS_TIME: 'SET_RENDEZVOUS_TIME' = 'SET_RENDEZVOUS_TIME'
export const MARK_RENDEZVOUS_UNSCHEDULABLE: 'MARK_RENDEZVOUS_UNSCHEDULABLE' = 'MARK_RENDEZVOUS_UNSCHEDULABLE'
export const MARK_AVAILABILITY_SUBMITTED: 'MARK_AVAILABILITY_SUBMITTED' = 'MARK_AVAILABILITY_SUBMITTED'
export const UPDATE_LIKE_STATUS: 'UPDATE_LIKE_STATUS' = 'UPDATE_LIKE_STATUS'
export const MARK_MATCH_FEEDBACK_SUBMITTED: 'MARK_MATCH_FEEDBACK_SUBMITTED' = 'MARK_MATCH_FEEDBACK_SUBMITTED'
export const GET_ADMIN_STATS_SUCCESS: 'GET_ADMIN_STATS_SUCCESS' = 'GET_ADMIN_STATS_SUCCESS'
export const MARK_DISLIKE_MATCH_FEEDBACK_SUBMITTED: 'MARK_DISLIKE_MATCH_FEEDBACK_SUBMITTED' =
  'MARK_DISLIKE_MATCH_FEEDBACK_SUBMITTED'
export const CLEAR_MATCH: 'CLEAR_MATCH' = 'CLEAR_MATCH'
